printWidth: 100
tabWidth: 2
useTabs: false
semi: false
singleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
overrides:
  - files:
      - "*.md"
      - README
    options:
      parser: markdown-nocjsp
      quickFix: true
  - files:
      - "*.mdx"
    options:
      parser: mdx-nocjsp
      quickFix: true
